from __future__ import annotations

import argparse
import re
from pathlib import Path

import numpy as np


FILE_RE = re.compile(r"^(?P<plot>dro|oc|rc)_(?P<tree>\d+)_pc\.txt$")
PLOT_TO_OUTPUT = {
    "dro": "AUS01",
    "oc": "AUS02",
    "rc": "AUS03",
}
SPLITS = ("train", "test", "validation")


def write_binary_ply(path: Path, data: np.ndarray, comments: list[str] | None = None) -> None:
    comments = comments or []
    header = [
        "ply",
        "format binary_little_endian 1.0",
        "comment Generated by convert_tls_tropical_leaf_wood.py",
        *[f"comment {comment}" for comment in comments],
        f"element vertex {len(data)}",
        "property float64 x",
        "property float64 y",
        "property float64 z",
        "property int label",
        "property int instance_id",
        "end_header",
    ]
    with path.open("wb") as f:
        f.write(("\n".join(header) + "\n").encode("ascii"))
        f.write(data.tobytes())


def load_tree_points(path: Path, instance_id: int) -> np.ndarray:
    arr = np.loadtxt(path, dtype=np.float64)
    if arr.ndim == 1:
        arr = arr.reshape(1, -1)
    if arr.shape[1] < 4:
        raise ValueError(f"{path} has {arr.shape[1]} columns, expected at least 4")

    out = np.empty(
        arr.shape[0],
        dtype=[
            ("x", "<f8"),
            ("y", "<f8"),
            ("z", "<f8"),
            ("label", "<i4"),
            ("instance_id", "<i4"),
        ],
    )
    out["x"] = arr[:, 0]
    out["y"] = arr[:, 1]
    out["z"] = arr[:, 2]
    out["label"] = np.rint(arr[:, 3]).astype(np.int32)
    out["instance_id"] = instance_id
    return out


def collect_plot_files(base_dir: Path) -> dict[str, list[Path]]:
    plot_files: dict[str, list[Path]] = {plot: [] for plot in PLOT_TO_OUTPUT}
    for split in SPLITS:
        split_dir = base_dir / split
        if not split_dir.exists():
            continue
        for path in sorted(split_dir.glob("*_pc.txt")):
            m = FILE_RE.match(path.name)
            if not m:
                continue
            plot_files[m.group("plot")].append(path)
    return plot_files


def convert(base_dir: Path, output_dir: Path) -> list[tuple[str, str, int, int]]:
    output_dir.mkdir(parents=True, exist_ok=True)
    summaries: list[tuple[str, str, int, int]] = []

    for plot in ("dro", "oc", "rc"):
        files = collect_plot_files(base_dir)[plot]
        if not files:
            continue

        chunks = []
        for path in files:
            m = FILE_RE.match(path.name)
            assert m is not None
            instance_id = int(m.group("tree"))
            chunks.append(load_tree_points(path, instance_id=instance_id))

        merged = np.concatenate(chunks)
        output_stem = PLOT_TO_OUTPUT[plot]
        output_path = output_dir / f"{output_stem}.ply"
        comments = [
            "country_iso3=AUS",
            f"plot_code={plot}",
            f"tree_count={len(files)}",
            "columns=x,y,z,label,instance_id",
            "instance_id=original_tree_number_from_filename",
        ]
        write_binary_ply(output_path, merged, comments=comments)
        summaries.append((plot, output_stem, len(files), len(merged)))

    return summaries


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert tls_tropical_leaf_wood TXT trees to plot-level binary PLY.")
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path("/Users/harryjfowen/Downloads/tls_tropical_leaf_wood"),
        help="Dataset root containing train/test/validation folders.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("/Users/harryjfowen/Downloads/tls_tropical_leaf_wood/ply_plots"),
        help="Output directory for AUS01..AUS03 binary PLY files.",
    )
    args = parser.parse_args()

    summaries = convert(args.input_dir, args.output_dir)
    for plot, output_stem, tree_count, point_count in summaries:
        print(f"{output_stem}.ply  plot={plot}  trees={tree_count}  points={point_count}")


if __name__ == "__main__":
    main()
