#!/usr/bin/env python3
"""Convert the German Dataverse LAZ files into binary little-endian PLY files.

The source LAZ files contain:
- xyz coordinates
- LAS classification (0/1 semantic classes)
- extra dimensions including Reflectance, Amplitude, Deviation

This script writes compact binary PLY files with columns:
- x, y, z          : float32
- reflectance      : float32
- label            : uint8

By default it exports the extra-dimension `Reflectance` field, not LAS `intensity`.
The output is written to a separate folder so it can be inspected before replacing
the existing `data/pool/deu*.ply` files.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

import laspy
import numpy as np


DEU_MAPPING = {
    "deu01": "QueRub_KA11_09_2019-09-03_q2_TLS-on_c.laz",
    "deu02": "QueRub_KA09_T053_2019-08-20_q1_TLS-on_c.laz",
    "deu03": "QuePet_BR01_01_2019-07-03_q2_TLS-on_c.laz",
    "deu04": "PinSyl_KA10_03_2019-07-30_q2_TLS-on_c.laz",
    "deu05": "PseMen_BR04_02_2019-07-04_q2_TLS-on_c.laz",
    "deu06": "PinSyl_KA09_T048_2019-08-20_q1_TLS-on_c.laz",
    "deu07": "PicAbi_BR08_01_2019-07-24_q1_TLS-on_c.laz",
    "deu08": "PicAbi_BR02_14_2019-06-25_q2_TLS-on_c.laz",
    "deu09": "FagSyl_BR05_P8T4_2019-07-10_q2_TLS-on_c.laz",
    "deu10": "FagSyl_BR01_01_2019-07-08_q1_TLS-on_c.laz",
    "deu11": "AcePse_SP02_04_2019-08-23_q2_TLS-on_c.laz",
}


def _localize_xyz(x: np.ndarray, y: np.ndarray, z: np.ndarray, frame: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    if frame == "none":
        return x, y, z
    if frame == "first":
        return x - x[0], y - y[0], z - z[0]
    if frame == "min":
        return x - x.min(), y - y.min(), z - z.min()
    if frame == "center_xy_min_z":
        return x - x.mean(), y - y.mean(), z - z.min()
    raise ValueError(f"Unknown local frame: {frame}")


def _write_binary_ply(path: Path, x: np.ndarray, y: np.ndarray, z: np.ndarray, reflectance: np.ndarray, label: np.ndarray, comments: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    n = int(x.shape[0])
    header = [
        "ply",
        "format binary_little_endian 1.0",
        "comment Generated by convert_deu_dataverse_laz_to_ply.py",
        *[f"comment {c}" for c in comments],
        f"element vertex {n}",
        "property float x",
        "property float y",
        "property float z",
        "property float reflectance",
        "property uchar label",
        "end_header",
    ]

    vertex_dtype = np.dtype([
        ("x", "<f4"),
        ("y", "<f4"),
        ("z", "<f4"),
        ("reflectance", "<f4"),
        ("label", "u1"),
    ])
    arr = np.empty(n, dtype=vertex_dtype)
    arr["x"] = x.astype(np.float32, copy=False)
    arr["y"] = y.astype(np.float32, copy=False)
    arr["z"] = z.astype(np.float32, copy=False)
    arr["reflectance"] = reflectance.astype(np.float32, copy=False)
    arr["label"] = label.astype(np.uint8, copy=False)

    with open(path, "wb") as f:
        f.write(("\n".join(header) + "\n").encode("ascii"))
        arr.tofile(f)


def _get_reflectance(las: laspy.LasData, field: str) -> np.ndarray:
    available = set(las.point_format.dimension_names)
    if field not in available:
        raise ValueError(f"Reflectance field '{field}' not found. Available dimensions: {sorted(available)}")
    return np.asarray(getattr(las, field), dtype=np.float32)


def convert_one(input_path: Path, output_path: Path, reflectance_field: str, local_frame: str, invert_classification: bool) -> None:
    las = laspy.read(input_path)

    x = np.asarray(las.x, dtype=np.float64)
    y = np.asarray(las.y, dtype=np.float64)
    z = np.asarray(las.z, dtype=np.float64)
    x, y, z = _localize_xyz(x, y, z, local_frame)

    reflectance = _get_reflectance(las, reflectance_field)
    classification = np.asarray(las.classification, dtype=np.uint8)
    if invert_classification:
        label = (1 - classification).astype(np.uint8)
    else:
        label = classification.astype(np.uint8)

    comments = [
        f"source={input_path.name}",
        f"reflectance_field={reflectance_field}",
        f"local_frame={local_frame}",
        f"label={'1-classification' if invert_classification else 'classification'}",
    ]
    _write_binary_ply(output_path, x, y, z, reflectance, label, comments)

    uniq, counts = np.unique(label, return_counts=True)
    counts_str = ", ".join(f"{int(u)}:{int(c)}" for u, c in zip(uniq, counts))
    print(
        f"{input_path.name} -> {output_path.name} | "
        f"N={len(label):,} | refl=[{float(reflectance.min()):.2f},{float(reflectance.max()):.2f}] | "
        f"labels={counts_str}"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert DEU Dataverse LAZ files to compact binary PLY.")
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path.home() / "Downloads" / "dataverse_files",
        help="Directory containing the DEU Dataverse LAZ files.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data/pool_deu_regen"),
        help="Output directory for regenerated DEU PLY files.",
    )
    parser.add_argument(
        "--reflectance-field",
        type=str,
        default="Reflectance",
        choices=["Reflectance", "intensity", "Amplitude"],
        help="LAZ attribute to export as the PLY reflectance column.",
    )
    parser.add_argument(
        "--local-frame",
        type=str,
        default="center_xy_min_z",
        choices=["center_xy_min_z", "min", "first", "none"],
        help="How to translate xyz into a local frame.",
    )
    parser.add_argument(
        "--keep-classification",
        action="store_true",
        help="Keep LAS classification directly. Default behavior matches the current PLY convention: label = 1 - classification.",
    )
    args = parser.parse_args()

    missing = [name for name in DEU_MAPPING.values() if not (args.input_dir / name).exists()]
    if missing:
        raise FileNotFoundError(f"Missing {len(missing)} LAZ files in {args.input_dir}: {missing}")

    args.output_dir.mkdir(parents=True, exist_ok=True)

    for deu_name, laz_name in DEU_MAPPING.items():
        convert_one(
            input_path=args.input_dir / laz_name,
            output_path=args.output_dir / f"{deu_name}.ply",
            reflectance_field=args.reflectance_field,
            local_frame=args.local_frame,
            invert_classification=not args.keep_classification,
        )

    print(f"\nWrote {len(DEU_MAPPING)} regenerated PLY files to {args.output_dir}")


if __name__ == "__main__":
    main()
